version: "3"
services:
  signal_cli:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
       - MODE=json-rpc
    volumes:
      - "./.data/signal-cli:/home/.local/share/signal-cli"
    networks:
      - network
  bridge:
    image: bridge:latest
    build: .
    container_name: signal-telegram-bridge
    volumes:
      - "./.data/signal-cli:/signal-cli"
    networks:
      - network

networks:
  network:
